name: Generar Keystore FitTrack

on:
  workflow_dispatch:

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Generar keystore
        run: |
          keytool -genkeypair \
            -keystore fittrack.keystore \
            -alias fittrack \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass fittrack2024 \
            -keypass fittrack2024 \
            -dname "CN=FitTrack,OU=Dev,O=FitTrack,L=Lima,S=Lima,C=PE"

      - name: Mostrar keystore en base64
        run: |
          echo "=== COPIA TODO LO QUE ESTÁ ENTRE LAS LÍNEAS ==="
          echo "---INICIO---"
          base64 -w 0 fittrack.keystore
          echo ""
          echo "---FIN---"
