name: Obtener SHA1 FitTrack

on:
  workflow_dispatch:

jobs:
  sha1:
    runs-on: ubuntu-latest
    steps:
      - name: Restaurar keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > fittrack.keystore

      - name: Mostrar SHA-1
        run: |
          echo "=== SHA-1 DEL KEYSTORE ==="
          keytool -list -v \
            -keystore fittrack.keystore \
            -alias fittrack \
            -storepass fittrack2024 \
            -keypass fittrack2024 \
            | grep -A1 "SHA1:"
          echo "=== FIN ==="
